services:
  - type: web
    name: S381Project_Group46
    env: node
    region: oregon
    branch: main
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: "/"
    autoDeploy: true
